### PR TITLE
Fix Credentials Folder Location for Windows

### LINKED ISSUE #20: fails for credential helper
The setup script seems to expect credentials stored in cleartext.
```shellsession
$ ./scripts/setup.sh
jq: error: Could not open file /home/luism/.terraform.d/credentials.tfrc.json: No such file or directory
$ cat ~/.terraformrc
credentials_helper "keychain" {}
```

### LINKED ISSUE #27: Credentials Folder Not Found On Windows OS
The setup script fails with the following message when running it on Windows using GitBash. 
```sh
$ ./scripts/setup.sh
jq: error: Could not open file C:/Users/Claire Knutson/.terraform.d/credentials.tfrc.json: No such file or directory
```

The reason is that the `terraform login` command is[ using the $APPDATA environment variable](https://github.com/hashicorp/terraform/blob/0c7fda19064fa929a29c9aed8fb507d9daac40cd/internal/command/cliconfig/config_windows.go#L41), not $HOME when run on a Windows operating system. In conjunction with using a different folder, the subfolder name, `terraform.d` is [not prefixed with a period](https://github.com/hashicorp/terraform/blob/0c7fda19064fa929a29c9aed8fb507d9daac40cd/internal/command/cliconfig/config_windows.go#L34) like it is for Unix operating systems.

This was previously reported in issue #20 and is still unresolved. I'll open a PR on the `scripts/setup.sh` file in this repo to account for the differences.

### PR DESCRIPTION
**Pull request by clairevnext**
## Description
The setup script fails with the following message when running it on Windows using GitBash. This is reported in issue #27 
```sh
$ ./scripts/setup.sh
jq: error: Could not open file C:/Users/Claire Knutson/.terraform.d/credentials.tfrc.json: No such file or directory
```
The reason is that the terraform login command is[ using the $APPDATA environment variable](https://github.com/hashicorp/terraform/blob/0c7fda19064fa929a29c9aed8fb507d9daac40cd/internal/command/cliconfig/config_windows.go#L41), not `$HOME` when run on a Windows operating system. In conjunction with using a different folder, the subfolder name `terraform.d` is [not prefixed with a period](https://github.com/hashicorp/terraform/blob/0c7fda19064fa929a29c9aed8fb507d9daac40cd/internal/command/cliconfig/config_windows.go#L34) like it is for Unix operating systems.

## Testing plan
1. Run the `./scripts/setup.sh` using the following
- GitBash on Windows
- Cygwin on Windows
- Ubuntu using WSL2

2. Script should show a message beginning with `It looks like you may have run this script before!`

Fixes #27
Fixes #22
Fixes #20

### CODE REVIEW

**Review by tbehling — APPROVED** [review]
LGTM as a peer review.  Thanks for putting this together!

File: scripts/setup.sh [hunk 1]
```diff
@@ -78,7 +78,14 @@ TERRAFORM_VERSION=$(terraform version -json | jq -r '.terraform_version')
...
 # already!
-CREDENTIALS_FILE="$HOME/.terraform.d/credentials.tfrc.json"
+CREDS_FOLDER="$HOME/."
+
+# Credentials are located in App/Data/Roaming on Windows
+if [[ "$OSTYPE" =~ ^msys ]]; then
+    CREDS_FOLDER="$APPDATA/"
+fi
+
+CREDENTIALS_FILE="${CREDS_FOLDER}terraform.d/credentials.tfrc.json"
```
Comment (brandonc) [inline scripts/setup.sh:88]: I am concerned that msys isn't the only OSTYPE that is possible on Windows, but I don't know enough to detect other values here. I was also slightly confused by the "." character as part of the FOLDER variable, so I came up with a slight alternative that just spells out the entire path based on OSTYPE:

```suggestion
# Credentials are located in App/Data/Roaming on Windows
if [[ "$OSTYPE" =~ ^msys ]]; then
    CREDENTIALS_FILE="$APPDATA/terraform.d/credentials.tfrc.json"
else
    CREDENTIALS_FILE="$HOME/.terraform.d/credentials.tfrc.json"
fi
```

Another suggestion would be to rename CREDS_FOLDER to be more clear:

```suggestion
CREDS_PREFIX="$HOME/."

# Credentials are located in App/Data/Roaming on Windows
if [[ "$OSTYPE" =~ ^msys ]]; then
    CREDS_PREFIX="$APPDATA/"
fi

CREDENTIALS_FILE="${CREDS_PREFIX}terraform.d/credentials.tfrc.json"
```

**Review by brandonc — APPROVED** [review]
Thanks for taking the time to fix this! My feedback is not blocking but let me know what you think.

File: scripts/setup.sh (hunk 1 above)
Comment (clairevnext) [reply scripts/setup.sh]: @brandonc, thanks for the feedback. Both suggestions have been incorporated. Further research on values for `$OSTYPE` shows that `cygwin` and `win32` are also possible. 

The `win32` value wasn't able to be tested but it is included since the Terraform CLI has a download for 32-bit Windows systems.

**Review by brandonc — APPROVED** [review]
